/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PerbankanView;

import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import perbankan.*;
import PerbankanView.*;

/**
 *
 * @author Dukhaan
 */
public class BankView1 extends javax.swing.JPanel {

    public DefaultTableModel model;
    private boolean isTableClicked = false;
    private MainFrame mainFrame;
    private Bank bank;

    /**
     * Creates new form BankView
     */
    public BankView1(MainFrame mainFrame) {
        bank = DatabaseService.getBank();
        initComponents();
        initTable();
        this.mainFrame = mainFrame;
        buttonEdit.setVisible(false);
        buttonHapus.setVisible(false);
        buttonBatal.setVisible(false);
        buttonSimpan.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonEdit = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        buttonSimpanUang = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        buttonAmbilUang = new javax.swing.JButton();
        inputNamaAwal = new javax.swing.JTextField();
        buttonSimpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableNasabah = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        inputNamaAkhir = new javax.swing.JTextField();
        buttonBatal = new javax.swing.JButton();

        buttonEdit.setBackground(new java.awt.Color(255, 153, 0));
        buttonEdit.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        buttonEdit.setForeground(new java.awt.Color(255, 255, 255));
        buttonEdit.setText("Edit");
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });

        buttonHapus.setBackground(new java.awt.Color(209, 26, 42));
        buttonHapus.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        buttonHapus.setForeground(new java.awt.Color(255, 255, 255));
        buttonHapus.setText("Hapus");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel1.setText("Tambah Nasabah");

        buttonSimpanUang.setBackground(new java.awt.Color(51, 153, 255));
        buttonSimpanUang.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        buttonSimpanUang.setForeground(new java.awt.Color(255, 255, 255));
        buttonSimpanUang.setText("Simpan Uang");
        buttonSimpanUang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanUangActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Nama Awal :");

        buttonAmbilUang.setBackground(new java.awt.Color(51, 153, 255));
        buttonAmbilUang.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        buttonAmbilUang.setForeground(new java.awt.Color(255, 255, 255));
        buttonAmbilUang.setText("Ambil Uang");
        buttonAmbilUang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAmbilUangActionPerformed(evt);
            }
        });

        inputNamaAwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNamaAwalActionPerformed(evt);
            }
        });

        buttonSimpan.setBackground(new java.awt.Color(51, 153, 255));
        buttonSimpan.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        buttonSimpan.setForeground(new java.awt.Color(255, 255, 255));
        buttonSimpan.setText("Simpan");
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });
        buttonSimpan.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                buttonSimpanVetoableChange(evt);
            }
        });

        tableNasabah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama Awal", "Nama Akhir", "Saldo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableNasabah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNasabahMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableNasabah);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Nama Akhir :");

        inputNamaAkhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNamaAkhirActionPerformed(evt);
            }
        });
        inputNamaAkhir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputNamaAkhirKeyReleased(evt);
            }
        });

        buttonBatal.setBackground(new java.awt.Color(153, 153, 153));
        buttonBatal.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        buttonBatal.setForeground(new java.awt.Color(255, 255, 255));
        buttonBatal.setText("Batal");
        buttonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonSimpanUang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonAmbilUang, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(inputNamaAwal))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(buttonSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(buttonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(27, 27, 27)
                                                .addComponent(buttonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(140, 140, 140))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(283, 283, 283)
                                                .addComponent(buttonBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(inputNamaAkhir))))))
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(385, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(367, 367, 367))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputNamaAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputNamaAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(buttonSimpanUang, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonAmbilUang, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        // Mendapatkan indeks baris yang dipilih
        int selectedRow = tableNasabah.getSelectedRow();

        // Pastikan ada baris yang dipilih sebelum mencoba mengedit
        if (selectedRow >= 0) {
            // Mendapatkan model tabel dari tableNasabah
            DefaultTableModel model = (DefaultTableModel) tableNasabah.getModel();

            // Mendapatkan nilai dari inputNamaAwal dan inputNamaAkhir
            String teksNamaAwal = inputNamaAwal.getText();
            String teksNamaAkhir = inputNamaAkhir.getText();

            // Memeriksa apakah inputNamaAwal atau inputNamaAkhir kosong
            if (teksNamaAwal.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nama Awal harus diisi.", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (teksNamaAkhir.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nama Akhir harus diisi.", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                // Mengganti data dalam baris yang dipilih dengan nilai inputNamaAwal dan inputNamaAkhir
                model.setValueAt(teksNamaAwal, selectedRow, 1); // Mengganti kolom "Nama Awal"
                model.setValueAt(teksNamaAkhir, selectedRow, 2); // Mengganti kolom "Nama Akhir"

                // Membersihkan inputNamaAwal dan inputNamaAkhir setelah mengedit
                inputNamaAwal.setText("");
                inputNamaAkhir.setText("");
            }
        } else {
            // Jika tidak ada baris yang dipilih, tampilkan pesan kesalahan atau tindakan lain yang sesuai
            JOptionPane.showMessageDialog(this, "Pilih baris yang akan diedit.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonEditActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        // Mendapatkan indeks baris yang dipilih
        int selectedRow = tableNasabah.getSelectedRow();

        // Pastikan ada baris yang dipilih sebelum mencoba menghapus
        if (selectedRow >= 0) {
            // Mendapatkan model tabel dari tableNasabah
            DefaultTableModel model = (DefaultTableModel) tableNasabah.getModel();

            // Menghapus baris yang dipilih dari model tabel
            model.removeRow(selectedRow);
        } else {
            // Jika tidak ada baris yang dipilih, tampilkan pesan kesalahan atau tindakan lain yang sesuai
            JOptionPane.showMessageDialog(this, "Pilih baris yang akan dihapus.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void buttonSimpanUangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanUangActionPerformed
        mainFrame.showView(new TambahUangView(mainFrame, bank.getNasabah(tableNasabah.getSelectedRow())));
    }//GEN-LAST:event_buttonSimpanUangActionPerformed

    private void buttonAmbilUangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAmbilUangActionPerformed
        mainFrame.showView(new TarikUangView(mainFrame, bank.getNasabah(tableNasabah.getSelectedRow())));
    }//GEN-LAST:event_buttonAmbilUangActionPerformed

    private void inputNamaAwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNamaAwalActionPerformed
        String teksNamaAwal = inputNamaAwal.getText();
        Nasabah nasabah = new Nasabah(teksNamaAwal, "");
    }//GEN-LAST:event_inputNamaAwalActionPerformed

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed

        String teksNamaAwal = inputNamaAwal.getText();
        String teksNamaAkhir = inputNamaAkhir.getText();

        // Membuat objek Nasabah dengan nilai namaAwal dan namaAkhir yang sesuai
        Nasabah nasabah = new Nasabah(teksNamaAwal, teksNamaAkhir);
        
        bank.tambahNasabah(teksNamaAwal, teksNamaAkhir);

        // Mendapatkan model tabel dari tableNasabah
        model = (DefaultTableModel) tableNasabah.getModel();

        // Menambahkan data nasabah ke dalam tabel sebagai baris baru
        model.addRow(new Object[]{model.getRowCount() + 1, nasabah.getNamaAwal(), nasabah.getNamaAkhir()});

        // Membersihkan inputNamaAwal dan inputNamaAkhir setelah menyimpan
        inputNamaAwal.setText("");
        inputNamaAkhir.setText("");
    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void initTable() {
        model = (DefaultTableModel) tableNasabah.getModel();
        for (int i = 0; i < bank.getJumlahNasabah(); i++) {
            Nasabah nasabah = bank.getNasabah(i);
            model.addRow(new Object[]{model.getRowCount() + 1, nasabah.getNamaAwal(), nasabah.getNamaAkhir(), nasabah.getTabungan().getSaldo()});
        }
    }

    private void tableNasabahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNasabahMouseClicked
        int selectedRow = tableNasabah.getSelectedRow();
        int columnIndexSaldo = 3;

        // Pastikan ada baris yang dipilih sebelum mencoba mengisi input
        if (selectedRow >= 0) {
            // Mendapatkan model tabel dari tableNasabah
            DefaultTableModel model = (DefaultTableModel) tableNasabah.getModel();

            // Mendapatkan nilai dari kolom "Nama Awal" dan "Nama Akhir" dari baris yang dipilih
            String namaAwal = model.getValueAt(selectedRow, 1).toString();
            String namaAkhir = model.getValueAt(selectedRow, 2).toString();

            // Mengisi inputNamaAwal dan inputNamaAkhir dengan nilai yang dipilih
            inputNamaAwal.setText(namaAwal);
            inputNamaAkhir.setText(namaAkhir);
        }

        // Jika ada baris yang dipilih, atur isTableClicked menjadi true dan tampilkan tombol-tombol yang sesuai
        if (selectedRow >= 0) {
            isTableClicked = true;
            buttonEdit.setVisible(true);
            buttonHapus.setVisible(true);
            buttonBatal.setVisible(true);
            buttonSimpan.setVisible(false);
        } else {
            // Jika tidak ada baris yang dipilih, atur isTableClicked menjadi false dan sembunyikan tombol-tombol
            isTableClicked = false;
            buttonEdit.setVisible(false);
            buttonHapus.setVisible(false);
            buttonBatal.setVisible(false);
            buttonSimpan.setVisible(true);
        }
    }//GEN-LAST:event_tableNasabahMouseClicked

    private void inputNamaAkhirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNamaAkhirActionPerformed
        String teksNamaAkhir = inputNamaAkhir.getText();
        Nasabah nasabah = new Nasabah("", teksNamaAkhir);
    }//GEN-LAST:event_inputNamaAkhirActionPerformed

    private void inputNamaAkhirKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNamaAkhirKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            // Jika tombol "Enter" ditekan, lakukan tindakan yang sama seperti tombol "Simpan"
            buttonSimpanActionPerformed(new ActionEvent(this, ActionEvent.ACTION_PERFORMED, ""));
        }
    }//GEN-LAST:event_inputNamaAkhirKeyReleased

    private void buttonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBatalActionPerformed
        inputNamaAwal.setText("");
        inputNamaAkhir.setText("");

        if (isTableClicked) {
            buttonEdit.setVisible(false);
            buttonHapus.setVisible(false);
            buttonBatal.setVisible(false);
            buttonSimpan.setVisible(true);
        }
        //        else {
        //            buttonEdit.setVisible(false);
        //            buttonHapus.setVisible(false);
        //            buttonBatal.setVisible(false);
        //            buttonSimpan.setVisible(false);
        //        }
    }//GEN-LAST:event_buttonBatalActionPerformed

    private void buttonSimpanVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_buttonSimpanVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSimpanVetoableChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAmbilUang;
    private javax.swing.JButton buttonBatal;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JButton buttonSimpanUang;
    private javax.swing.JTextField inputNamaAkhir;
    private javax.swing.JTextField inputNamaAwal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tableNasabah;
    // End of variables declaration//GEN-END:variables
}
