/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PerbankanView;

import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import perbankan.*;
import PerbankanView.*;

/**
 *
 * @author Dukhaan
 */
public class TambahUangView extends javax.swing.JPanel {

    private javax.swing.JTable tableNasabah;
    private MainFrame mainFrame;
    private Nasabah nasabah;

    /**
     * Creates new form TambahUangView
     */
    public TambahUangView(MainFrame mainFrame, Nasabah nasabah) {
        initComponents();
        this.mainFrame = mainFrame;
        this.nasabah = nasabah;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inputSimpanUang = new javax.swing.JTextField();
        buttonSimpanSimpan = new javax.swing.JButton();
        buttonKembaliSimpan = new javax.swing.JButton();

        setBackground(new java.awt.Color(36, 34, 49));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Simpan Uang");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Masukkan uang :");

        inputSimpanUang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSimpanUangActionPerformed(evt);
            }
        });

        buttonSimpanSimpan.setText("Simpan");
        buttonSimpanSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanSimpanActionPerformed(evt);
            }
        });

        buttonKembaliSimpan.setText("Kembali");
        buttonKembaliSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKembaliSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputSimpanUang, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonSimpanSimpan)
                .addGap(33, 33, 33)
                .addComponent(buttonKembaliSimpan)
                .addGap(223, 223, 223))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputSimpanUang, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSimpanSimpan)
                    .addComponent(buttonKembaliSimpan))
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inputSimpanUangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSimpanUangActionPerformed

        Bank bank = new Bank();

        String newSaldo = inputSimpanUang.getText();

        try {
            // Mengonversi newSaldo menjadi tipe data integer
            int jumlahSaldo = Integer.parseInt(newSaldo);
            int selectedRow = tableNasabah.getSelectedRow();

            if (selectedRow >= 0) {
                int rowIndex = tableNasabah.convertRowIndexToModel(selectedRow);

                if (nasabah != null) {
                    Tabungan tabungan = nasabah.getTabungan();

                    if (jumlahSaldo <= 0) {
                        JOptionPane.showMessageDialog(this, "Jumlah saldo yang akan disimpan harus lebih dari 0.", "Error", JOptionPane.ERROR_MESSAGE);
                    } else {
                        tabungan.simpanUang(jumlahSaldo);

                        DefaultTableModel model = (DefaultTableModel) tableNasabah.getModel();
                        model.setValueAt(tabungan.getSaldo(), selectedRow, 3);

                        inputSimpanUang.setText("");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Pilih baris Nasabah yang akan menambahkan saldo.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Masukkan jumlah saldo yang valid.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_inputSimpanUangActionPerformed

    private void buttonSimpanSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanSimpanActionPerformed

        if (nasabah != null) {
            // Memeriksa apakah inputSaldo kosong atau tidak
            if (inputSimpanUang.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Isi jumlah saldo yang akan disimpan.", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                try {
                    // Mendapatkan jumlah saldo yang akan disimpan dari inputSaldo
                    String jumlahSimpan = inputSimpanUang.getText(); // Mengubah ke String
                    JOptionPane.showMessageDialog(this, "Saldo berhasil disimpan.", "Success", JOptionPane.OK_OPTION);

                    // Memastikan jumlahSimpan positif
                    int saldoTambahan = Integer.parseInt(jumlahSimpan);
                    if (saldoTambahan <= 0) {
                        JOptionPane.showMessageDialog(this, "Jumlah saldo yang akan disimpan harus lebih dari 0.", "Error", JOptionPane.ERROR_MESSAGE);
                    } else {
                        // Mendapatkan objek Tabungan dari Nasabah
                        Tabungan tabungan = nasabah.getTabungan();

                        // Menyimpan saldo sesuai dengan jumlahSimpan
                        tabungan.simpanUang(saldoTambahan);

                        // Mengosongkan inputSaldo
                        inputSimpanUang.setText("");
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Masukkan jumlah saldo yang valid.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        mainFrame.showView(new BankView(mainFrame));
    }//GEN-LAST:event_buttonSimpanSimpanActionPerformed

    private void buttonKembaliSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembaliSimpanActionPerformed
        mainFrame.showView(new BankView(mainFrame));
    }//GEN-LAST:event_buttonKembaliSimpanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonKembaliSimpan;
    private javax.swing.JButton buttonSimpanSimpan;
    private javax.swing.JTextField inputSimpanUang;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
